version: 2

jobs:
    lint:
        docker:
            - image:          circleci/php
        steps:
            - checkout
            - run: composer install
            - run: |
                mkdir -p test-results
                composer lint -- --report=junit --report-file=test-results/phpcs.xml
            - store_test_results:
                path: test-results

    codecept:
        working_directory:    /var/www/html/wp-content/plugins/simple-csv-exporter
        docker:
            # TODO: Switch to tagged version when stable
            - image:          ryanshoover/wp-browser:latest
              name:           wp-browser
              environment:
                DB_USER:      wordpress
                DB_PASSWORD:  wordpress
                DB_NAME:      wordpress
                DB_HOST:      db

            - image:          circleci/mysql:5
              name:           db
              environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE:      wordpress
                MYSQL_USER:          wordpress
                MYSQL_PASSWORD:      wordpress
        steps:
            - checkout

            - run:
                name:         Link tests to site root
                command:      |
                    ln -s "$PWD/tests" /var/www/html/tests

            - run:
                name:         Make sure WordPress is loaded.
                command:      /entrypoint.sh

            # Run the test scripts
            - run:
                name:         Run Codeception tests.
                command:      codecept run --xml="results.xml"

            # Open up our test results to CircleCI
            - store_test_results:
                path:         tests/_output

    deploy:
        docker:
            - image: circleci/php:7-fpm-node

        steps:
            - checkout
            - run: sudo apt-get update && sudo apt-get install subversion

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "README.txt" }}
                    - v1-dependencies-

            - run:
                name:    Install composer
                command: |
                    if [ -f ./composer.json ]; then
                        composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader
                    fi

            - run:
                name: Install yarn
                command: |
                    if [ -f ./package.json ]; then
                        yarn install --production --non-interactive --emoji false
                    fi

            - save_cache:
                key: v1-dependencies-{{ checksum "README.txt" }}
                paths:
                    - node_modules
                    - vendor

            - run:
                name: Run yarn run build
                command: |
                    if yarn run --non-interactive | grep -e "- build"; then
                        yarn run build
                    fi

            - run:
                name: Clean up things we don't need to ship
                command: rm -rf node_modules .circleci .git* tests

            - run:
                name: Set up plugin slug
                command: |
                    echo '[[ $PLUGIN_SLUG ]] && \
                        export PLUGIN_SLUG=$PLUGIN_SLUG || \
                        export PLUGIN_SLUG=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV

            - run:
                name: Checkout SVN version of plugin
                command: |
                    mkdir -p ~/wordpress-svn
                    svn checkout --non-interactive https://plugins.svn.wordpress.org/$PLUGIN_SLUG ~/wordpress-svn

            - run:
                name: Add new plugin code in place of old
                command: |
                    rm -rf ~/wordpress-svn/trunk/{,.[!.],..?}*
                    cp -R . ~/wordpress-svn/trunk/

            - run:
                name: Check code into SVN
                command: |
                    cd ~/wordpress-svn/trunk/
                    if $( svn status | grep ^! ); then
                        svn status | grep ^! | awk '{print " --force "$2}' | xargs svn delete
                    fi
                    if [ -f .svnignore ]; then
                        svn propset svn:ignore -F .svnignore .
                    fi
                    svn add --force .
                    svn status

            - deploy:
                command: |
                    cd ~/wordpress-svn
                    if [[ $CIRCLE_TAG ]]; then
                        svn copy trunk tags/$CIRCLE_TAG;
                        svn commit --username $WP_USER --password $WP_PASS --non-interactive --message "Tagging $CIRCLE_TAG";
                    fi

workflows:
    version: 2
    test:
        jobs:
            - lint
            - codecept
    deploy:
        jobs:
            - deploy:
                context: wordpress-svn
                filters:
                    tags:
                        only: /[\d\.]*/
                    branches:
                        ignore: /.*/
